# IP_ADDRESS_OR_PREFIX  SERVER_TYPE
XXX.XXX.XXX             slurm
XXX.XXX.XXX.XXX         pbs_pro
XXX.XXX.XXX             pbs_special
XXX.XXX.XXX.XXX         sge

#for the server type, you can use "slurm", "pbs_pro", "pbs_sepcial", "sge", "pbs"